[package]
name = "blockhead"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
log = "0.4.22"
regex = "1.11.1"
serde_json = "1.0.133"
serde_yml = "0.0.12"
sqlite = "0.36.1"
tokio = { version = "1.42.0", features = ["full"] }
toml = "0.8.19"
